trigger:
  - main
  - develop
pool:
  vmImage: 'windows-latest'
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/ProjectName.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/ProjectName.csproj'
    arguments: '--no-restore'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--no-restore --no-build'
- task: DotNetCoreCLI@2
  displayName: 'Publish WebApi'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/ProjectName.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --runtime -r $(runtime)'
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
   PathtoPublish: $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Artifact: drop'